# Generated by Django 5.2.2 on 2025-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HTML5', 'HTML5 Game'), ('ESPORTS', 'eSports Info/Link'), ('INSTANT', 'Instant Game')], default='HTML5', max_length=10)),
                ('game_url', models.URLField(help_text='Link to play/embed the game, or for eSports info page.', max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Link to a thumbnail image for the game.', max_length=1024, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this game on special sections like homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
