# Generated by Django 5.2.2 on 2025-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Brief description of the item or offer.')),
                ('affiliate_url', models.URLField(help_text='The actual affiliate tracking link.', max_length=2048)),
                ('image_url', models.URLField(blank=True, help_text='URL of a promotional image.', max_length=2048, null=True)),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('SERVICES', 'Services'), ('TRAINING', 'Training & Courses'), ('BOOKS', 'Books'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active items will be displayed to users.')),
                ('display_priority', models.IntegerField(db_index=True, default=0, help_text='Higher numbers display first. Used for ordering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-display_priority', '-created_at'],
            },
        ),
    ]
