# Generated by Django 5.2.2 on 2025-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_affiliateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerBankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='e.g., Equity Bank', max_length=255)),
                ('account_holder_name', models.CharField(help_text='e.g., John Doe', max_length=255)),
                ('account_number', models.CharField(help_text='e.g., 0123456789012', max_length=100)),
                ('swift_bic', models.CharField(blank=True, help_text='SWIFT/BIC code, e.g., EQBLKENAXXX', max_length=20, null=True)),
                ('iban', models.CharField(blank=True, help_text='IBAN, if applicable', max_length=50, null=True)),
                ('branch_info', models.CharField(blank=True, help_text='e.g., Main Branch, Nairobi', max_length=255, null=True)),
                ('payment_instructions', models.TextField(blank=True, help_text="e.g., 'Please use your GlobalMeetup username or email as the payment reference.'")),
                ('is_active', models.BooleanField(default=False, help_text='Enable this to make these details visible on the site. Only one set of details can be active at any time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner Banking Detail',
                'verbose_name_plural': 'Owner Banking Details',
                'ordering': ['-updated_at'],
            },
        ),
    ]
